### ISSUE TITLE
Replicate not working when we have folders

### ISSUE THREAD

**Issue by abhimanyuvarma** [hashicorp/consul-replicate#27]
I have two data centers dc1 and dc2 , dc2 being the master . If I have a folder common to house my common KVs , and inside common , I have two properties test1=123, test2=456  and try to replicate the same across to dc1 , three properties with the following names are created in dc1 - "common\test1" common\test2 and common(a kv for folder is also created),but when you click on these properties - they give a 404. No folder is created either.
If I dont have any folder structure , KVs sync up fine.

I used the following common to start consul replicate 

consul-replicate -prefix "common@dc2" -consul "dc1 server ip:port"  log-level debug 

In the logs , i saw it actually picks up three properties instead of 2.

**Comment by abhimanyuvarma** [comment]
@sethvargo - I hope I am doing it the right way . 

Thanks in advance,
Abhimanyu.

**Comment by sethvargo** [comment]
Can you please share the logs in debug mode?

**Comment by abhimanyuvarma** [comment]
![image](https://cloud.githubusercontent.com/assets/14974606/10474301/b47f6b64-7252-11e5-9b05-24a726d7a852.png)
 This created two keys one global\test123 and global(which was a folder on dc2)

**Comment by abhimanyuvarma** [comment]
![image](https://cloud.githubusercontent.com/assets/14974606/10477332/f9026582-7272-11e5-98f1-5cc5a71a803a.png)

**Comment by daveadams** [comment]
This seems to be because the code to build the destination KV path was using `filepath.Join()` to build the path, but since Consul KV is not actually a filesystem, the semantics are wrong, and it caused a lot of little issues. So if you're running on Windows, the filepath.Join() function will use backslashes to join rather than slashes. PR #41 should fix this (although I don't have a Windows machine to easily test with).
